# Generated by Django 3.2.7 on 2021-09-17 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='title_more',
            field=models.CharField(default=0, max_length=150, verbose_name='Полное название'),
        ),
    ]
